config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users

    root 'home#index', defaults: { page_title: 'about_us' }
    get 'about_us' => 'home#index', as: :about_us, defaults: { page_title: 'about_us' }
    get 'contacts' => 'home#index', as: :contacts, defaults: { page_title: 'contacts' }
    get 'services' => 'home#services', as: :services
    get 'projects' => 'home#projects', as: :projects
    get 'project/:id' => 'home#project', as: :project

    namespace :admin do
      get '/' => 'pages#index'
      resources :pages do
        resources :page_images, except: [:index, :show] do
          post 'sort', on: :collection
        end
      end
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable
end

app/views/admin/pages/_form.html.slim
.panel.panel-default
  .panel-body
    = simple_form_for([:admin, @page]) do |f|
      = f.error_notification
      .form-inputs
        - if @page.project?
          #page-tag-list-container
            = hidden_field_tag 'tags_list', @page.tag_list.join(', '), data: { all_tags: get_tags }
        - else
          = f.input :page_title, label: 'Select page type', collection: Page.page_titles.keys
        br
        = f.hidden_field :page_type
        p
          - I18n.available_locales.each do |locale|
            = link_to locale, { locale: locale }, { class: "btn btn-default btn-sm #{ 'active' if I18n.locale == locale } add-right-space", role: 'button' }
        = f.input :title
        = f.input :description
        = f.input :content, as: :ckeditor
      .form-actions
        = f.button :submit, class: 'btn-primary btn-sm'

.panel.panel-default
  .panel-body
    h4 Images
    .page-images
      - if @page.new_record?
        | You will be able create images only after creating page.
      - else
        ul id="sortable" data-update-url="#{sort_admin_page_page_images_url(@page)}"
          = render @page.page_images
        br
        = link_to 'Add image', new_admin_page_page_image_path(@page), remote: true, class: 'btn-primary btn-sm'

javascript:
  $(function() {
    initializers.bootstrapTags();
    initializers.sortable();
  });

app/views/admin/pages/edit.html.slim
h1 = "Editing #{@page.page_type}"
= render 'form'
br
= link_to 'Show', admin_page_path(@page), class: 'btn btn-info btn-sm add-right-space'
= link_to 'Back', admin_pages_path(page_type: @page.page_type), class: 'btn btn-default btn-sm'

app/views/admin/pages/index.html.slim
h1 = "Listing #{@page_type.pluralize}"

table.table.table-striped
  thead
    tr
      th Title
      th Description
      th Actions
      th
      th
  tbody
    - @pages.each do |page|
      tr
        td = page.title
        td = page.description
        td = link_to 'Show', admin_page_path(page), class: 'btn btn-default btn-xs'
        td = link_to 'Edit', edit_admin_page_path(page), class: 'btn btn-xs btn-primary'
        td = link_to 'Destroy', admin_page_path(page), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger'

= link_to "New #{@page_type}", new_admin_page_path(page_type: @page_type), class: 'btn btn-xs btn-primary'

app/views/admin/pages/new.html.slim
h1 = "New #{@page.page_type}"

= render 'form'
br
= link_to 'Back', admin_pages_path(page_type: @page.page_type), class: 'btn btn-default btn-sm'

app/views/admin/pages/show.html.slim
p = @page.title
p = @page.description
p == @page.content

- if signed_in?
  = link_to 'Edit', edit_admin_page_path(@page), class: 'btn btn-primary btn-sm add-right-space'
  = link_to 'Back', admin_pages_path(page_type: @page.page_type), class: 'btn btn-default btn-sm'