config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users

    root 'home#index', defaults: { page_title: 'about_us' }
    get 'about_us' => 'home#index', as: :about_us, defaults: { page_title: 'about_us' }
    get 'contacts' => 'home#index', as: :contacts, defaults: { page_title: 'contacts' }
    get 'services' => 'home#services', as: :services
    get 'projects' => 'home#projects', as: :projects
    get 'project/:id' => 'home#project', as: :project

    namespace :admin do
      get '/' => 'pages#index'
      resources :pages do
        resources :page_images, except: [:index, :show] do
          post 'sort', on: :collection
        end
      end
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @page = Page.send(params[:page_title]).last
  end

  def project
    @project = Page.find(params[:id])
  end

  def projects
    @projects = Page.project.order(created_at: :desc).includes(:page_images)

    @projects = case params[:project_type]
    when 'commercial'
      @projects.tagged_with('project commercial')
    when 'private'
      @projects.tagged_with('project privat')
    when 'finished'
      @projects.tagged_with('project finished')
    else
      @projects
    end

    @projects
  end
end

app/views/home/_project_cell.html.slim
.project-preview.col-xs-12.col-sm-6.col-md-4.col-lg-3
  = link_to project_path(project.id) do
    .row
      .col-xs-12.project-img
        span.project-helper
        - if project.page_images.present?
          img src="#{project.page_images.first.file.url(:medium)}"
        - else
          = t('project.text')
      .col-xs-12.text-center
        span= project.title

app/views/home/index.html.slim
- if params[:page_title] == 'about_us'
  = render partial: 'shared/carousel', locals: { images: @page.try(:page_images) }
- else
  .row
    .col-xs-12
      == @page.content

app/views/home/project.html.slim
h4 = @project.title
.row.add-bottom-space
  - if @project.page_images.present?
    - @project.page_images.each_with_index do |image, index|
      / - if index > 1
      .project-img.add-bottom-space.col-xs-12.col-sm-6.col-md-4.col-lg-3
        span.project-helper
        a.test-popup-link href="#{image.file.url(:medium)}"
          img src="#{image.file.url(:medium)}"
.row
  .col-xs-12
    == @project.content

app/views/home/projects.html.slim
h3 = t('.title')

.row.add-bottom-space
  .col-xs-12
    = link_to(t('.commercial'), projects_path(project_type: 'commercial'), class: "project-type #{'active' if params['project_type'] == 'commercial'}")
    = link_to(t('.privat'), projects_path(project_type: 'private'), class: "project-type #{'active' if params['project_type'] == 'private'}")
    = link_to(t('.finished'), projects_path(project_type: 'finished'), class: "project-type #{'active' if params['project_type'] == 'finished'}")

.row.add-bottom-space
  == show_projects(@projects)

/ .row.add-bottom-space
/   .col-xs-12
/     h4 = t('.commercial')
/   == show_projects(@commercial_projects)

/ .row.add-bottom-space
/   .col-xs-12
/     h4 = t('.privat')
/   == show_projects(@privat_projects)

/ .row
/   .col-xs-12
/     h4 = t('.finished')
/   == show_projects(@finished_projects)