config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users

    root 'home#index', defaults: { page_title: 'about_us' }
    get 'about_us' => 'home#index', as: :about_us, defaults: { page_title: 'about_us' }
    get 'contacts' => 'home#index', as: :contacts, defaults: { page_title: 'contacts' }
    get 'services' => 'home#services', as: :services
    get 'projects' => 'home#projects', as: :projects
    get 'project/:id' => 'home#project', as: :project

    namespace :admin do
      get '/' => 'pages#index'
      resources :pages do
        resources :page_images, except: [:index, :show] do
          post 'sort', on: :collection
        end
      end
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable
end

app/models/page_image.rb
class PageImage < ActiveRecord::Base
  mount_uploader :file, PageImageUploader
  belongs_to :page
  acts_as_list scope: :page

  validates :title, presence: true, uniqueness: true
end

app/controllers/admin/page_images_controller.rb
class Admin::PageImagesController < Admin::AdminController
  before_filter :find_page_image, only: [:edit, :update, :destroy]
  before_filter :set_page, only: [:new, :create, :edit, :update]
  layout 'modal_actions'

  def new
    @page_image = @page.page_images.build
  end

  def create
    @page_image = PageImage.new(page_image_params.merge(page_id: params[:page_id]))
    @page_image.save ? render('create') : render('new')
  end

  def edit
  end

  def update
    @page_image.update(page_image_params)
    @page_image.save ? render('update') : render('edit')
  end

  def destroy
    @page_image.destroy
  end

  def sort
    PageImage.find(params[:id]).insert_at(params[:position].to_i + 1)
    render nothing: true
  end

  private

  def find_page_image
    @page_image = PageImage.find(params[:id]) if params[:id]
  end

  def set_page
    @page = Page.find(params[:page_id])
  end

  def page_image_params
    params.require(:page_image).permit(:title, :description, :file)
  end
end

app/controllers/page_images_controller.rb
class PageImagesController < ApplicationController
  before_filter :find_page_image, only: [:edit, :update, :destroy]
  before_filter :set_page, only: [:new, :create, :edit, :update]
  layout 'modal_actions'

  def new
    @page_image = @page.page_images.build
  end

  def create
    @page_image = PageImage.new(page_image_params.merge(page_id: params[:page_id]))
    @page_image.save ? render('create') : render('new')
  end

  def edit
  end

  def update
    @page_image.update(page_image_params)
    @page_image.save ? render('update') : render('edit')
  end

  def destroy
    @page_image.destroy
  end

  def sort
    PageImage.find(params[:id]).insert_at(params[:position].to_i + 1)
    render nothing: true
  end

  private

  def find_page_image
    @page_image = PageImage.find(params[:id]) if params[:id]
  end

  def set_page
    @page = Page.find(params[:page_id])
  end

  def page_image_params
    params.require(:page_image).permit(:title, :description, :file)
  end
end

app/views/admin/page_images/_form.html.slim
= simple_form_for([:admin, @page, @page_image], authenticity_token: true, remote: true) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :description
    - if params[:action] == 'new'
      = f.input :file

  .form-actions
    = f.button :submit, class: 'btn-primary btn-sm'

app/views/admin/page_images/_page_image.html.slim
= content_tag_for :li, page_image, class: 'ui-state-default', data: { image_id: page_image.id } do
  = image_tag page_image.file.thumb.url, class: 'add-right-space'
  span = page_image.title
  = link_to 'Edit', edit_admin_page_page_image_path(@page, page_image), remote: true, class: 'btn btn-primary pull-right btn-sm'
  = link_to 'Delete', admin_page_page_image_path(@page, page_image), method: :delete, remote: true, class: 'btn btn-danger pull-right btn-sm add-right-space'

app/views/admin/page_images/create.js.erb
modalActions.closeModalAndShowMessage('Зображення було добавлено.');
modalActions.insertImage('<%= render @page_image %>');

app/views/admin/page_images/destroy.js.erb
modalActions.closeModalAndShowMessage('Зображення було видалено.');
modalActions.deleteImage(<%= @page_image.id %>);

app/views/admin/page_images/edit.js.erb
modalActions.openModal("<%= j(content_tag(:div, render('form'), class: 'modal-body')) %>");
modalActions.setHeader('Edit image');

app/views/admin/page_images/new.js.erb
modalActions.openModal("<%= j(content_tag(:div, render('form'), class: 'modal-body')) %>");
modalActions.setHeader('New image');

app/views/admin/page_images/update.js.erb
modalActions.closeModalAndShowMessage('Зображення було оновлено.');
modalActions.updateImage(<%= @page_image.id %>, '<%= render @page_image %>');