config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users

    root 'home#index', defaults: { page_title: 'about_us' }
    get 'about_us' => 'home#index', as: :about_us, defaults: { page_title: 'about_us' }
    get 'contacts' => 'home#index', as: :contacts, defaults: { page_title: 'contacts' }
    get 'services' => 'home#services', as: :services
    get 'projects' => 'home#projects', as: :projects
    get 'project/:id' => 'home#project', as: :project

    namespace :admin do
      get '/' => 'pages#index'
      resources :pages do
        resources :page_images, except: [:index, :show] do
          post 'sort', on: :collection
        end
      end
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_tags
    ActsAsTaggableOn::Tag.pluck(:name)
  end

  def show_projects(projects)
    if projects.present?
      projects.map{ |pr| render(partial: 'project_cell', locals: { project: pr }) }.join(' ')
    else
      content_tag(:div, class: 'col-xs-12') do
        content_tag(:span, "На даний момент таких проектів немає.")
      end
    end
  end
end

app/views/application/_footer.html.haml
.footer
  .container.footer_body
    .left_footer.pull-left
      %p.pull-left Folow us:
      %ul.social_area.pull-left
        %li.pull-left
          = link_to 'Facebook', 'https://www.facebook.com/pages/KN-designstudio', class: 'facebook'
        %li.pull-left
          = link_to 'VK', 'http://vk.com/', class: 'vk'
        %li.pull-left
          = link_to 'Pinterest', 'https://www.pinterest.com/kndesignstudio/', class: 'pinterest'
        %li.pull-left
          = link_to 'Instagram', 'https://instagram.com/kn_studio/', class: 'instagram'
    .right_footer.pull-right
      %ul.phone_area.pull-right
        %li
          tel: 097 xxx xx xx
        %li
          tel: 093 xxx xx xx
      %p.pull-right Contact us:
  .bottom

app/views/application/_footer.html.slim
.footer
  .container.footer_body
    .left_footer.pull-left
      p.pull-left = t('footer.folow_us')
      ul.social_area.pull-left
        li.pull-left
          = link_to 'Facebook', 'https://www.facebook.com/KN-design-studio-398536467014903/', class: 'facebook'
        li.pull-left
          = link_to 'G+', 'https://plus.google.com/114873936626555080770/posts', class: 'gplus'
        li.pull-left
          = link_to 'Pinterest', 'https://www.pinterest.com/kndesignstudio/', class: 'pinterest'
        li.pull-left
          = link_to 'Instagram', 'https://instagram.com/kn_studio/', class: 'instagram'
    .right_footer.pull-right
      ul.phone_area.pull-right
        li
          | tel: 098 86 15 639
        li
          | tel: 093 00 84 228
      p.pull-right = t('footer.contact_us')
  .bottom

app/views/application/_header.html.slim
.pull-right.languages
  = link_to 'eng', locale: 'en'
  = " | "
  = link_to 'укр', locale: 'ua'
  - if signed_in?
    = " | "
    = link_to 'Log out', destroy_user_session_path, method: :delete
= image_tag 'logo2.png', size: '104x104', class: 'logo_img center-block'

nav.navbar
  #navbar
    ul.nav.navbar-nav
      li= link_to t('header.about_us'), root_path
      / li.dropdown
      /   = link_to 'Projects', '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown', 'aria-expanded' => 'true'
      /   ul.dropdown-menu.list-inline
      /     li= link_to 'All projects'
      /     li= link_to 'Commercial projects'
      /     li= link_to 'Second projects'
      /     li= link_to 'Third projects'
      / li= link_to t('header.services')
      li= link_to t('header.projects'), projects_path
      / li= link_to t('header.news')
      / li= link_to t('header.publications')
      li= link_to t('header.contacts'), contacts_path